export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Access",
  headline: "Book your favorite health professional faster with the Sensei app",
  description: "Available on iOS and Android.",
  buttonLabel: "Download the app",
  imgStart: true,
  img: require("../../images/doc3.svg"),
  alt: "Doctor",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Access",
  headline: "Unlimited Access with zero fees",
  description: "Get access to our qualified medics on a real time.",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/doc3.svg"),
  alt: "Doctor",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjThree = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Access",
  headline: "Unlimited Access with zero fees",
  description: "Get access to our qualified medics on a real time.",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/doc3.svg"),
  alt: "Doctor",
  dark: true,
  primary: true,
  darkText: false,
};
